module.exports = [
  {
    key: 'visualizar.portaria',
    name: 'Visualizar Portaria',
    description: 'Visualizar Portaria',
    enabled: true,
    role: ['guest', 'servidor', 'admin'],
  },
  {
    key: 'criar.portaria',
    name: 'Criar Portaria',
    description: 'Criar Portaria',
    enabled: true,
    role: ['servidor', 'admin'],
  },
  {
    key: 'editar.portaria',
    name: 'Editar Portaria',
    description: 'Editar Portaria',
    enabled: true,
    role: ['servidor', 'admin'],
  },
  {
    key: 'excluir.portaria',
    name: 'Excluir Portaria',
    description: 'Excluir Portaria',
    enabled: true,
    role: ['servidor', 'admin'],
  },
  {
    key: 'visualizar.usuario',
    name: 'Visualizar Usuário',
    description: 'Visualizar Usuário',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'visualizar.usuarios',
    name: 'Visualizar Usuários',
    description: 'Visualizar Usuários',
    enabled: true,
    role: ['servidor', 'admin'],
  },
  {
    key: 'criar.usuario',
    name: 'Criar Usuário',
    description: 'Criar Usuário',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'editar.usuario',
    name: 'Editar Usuário',
    description: 'Editar Usuário',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'excluir.usuario',
    name: 'Excluir Usuário',
    description: 'Excluir Usuário',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'visualizar.permissao',
    name: 'Visualizar Permissão',
    description: 'Visualizar Permissão',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'criar.permissao',
    name: 'Criar Permissão',
    description: 'Criar Permissão',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'editar.permissao',
    name: 'Editar Permissão',
    description: 'Editar Permissão',
    enabled: true,
    role: ['admin'],
  },
  {
    key: 'criar.permissao',
    name: 'Excluir Permissão',
    description: 'Excluir Permissão',
    enabled: true,
    role: ['admin'],
  },
];
